#! /bin/bash

#rm *.class
#rm view/*.class
#rm model/*.class
#rm control/*.class

echo ""
echo "DELETING OLD CLASS FILES"

rm -f *.class 
rm -rf */*.class

echo ""
echo "COMPILING APP"
javac App.java

echo ""
echo "RUNING APP"
java App

echo ""
echo "DELETING CLASS FILES"
rm -f *.class 
rm -rf */*.class

echo ""
echo "DONE"
echo ""
